program: scripts/sweep_train.py
method: bayes  
metric:
  name: val_accuracy
  goal: maximize
parameters:
  model_type:
    values: ["BiLSTM"]       #, "CNN"
  embedding_dim:
    values: [64, 128]        # for CNN [128, 256]
  dropout:
    values: [0.2, 0.5]
  dense_units:
    values: [32, 64]
  learning_rate:
    values: [0.001, 0.0005]
  batch_size:
    values: [128]
  epochs:
    value: 5
  num_filters:                # only used in the CNN branch
    values: [64, 128]
  kernel_size:                # only used in the CNN branch
    values: [3, 5]
  lstm_units:                  # only used in the BiLSTM branch
    values: [64, 128]
  optimizer:
    values: ["adam", "rmsprop"]
